export const PROGRESSION = Object.freeze({
  initialLevel: 10,
  maxLevel: 100,
  trainingMin: 1,
  trainingMax: 3,
  travelLevels: 0,
  gymVictoryLevels: 1,
  leagueVictoryLevels: 1,
  ambushVictoryLevels: 0,
  gymCatchupThreshold: 10,
  gymCatchupLevels: 6,
  earlyTargetLevel: 10,
  leagueFirstLevel: 50,
  leagueLevelStep: 3,
  aceBonus: 2,
  captureMinLevel: 8,
  captureTargetOffset: -1,
  captureLevelSpread: 3,
});
